################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Device/Common\ Sources/device.obj: ../Device/Common\ Sources/device.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/device.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_adc.obj: ../Device/Common\ Sources/f2838x_adc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_adc.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_codestartbranch.obj: ../Device/Common\ Sources/f2838x_codestartbranch.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_codestartbranch.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_cputimers.obj: ../Device/Common\ Sources/f2838x_cputimers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_cputimers.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_defaultisr.obj: ../Device/Common\ Sources/f2838x_defaultisr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_defaultisr.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_dma.obj: ../Device/Common\ Sources/f2838x_dma.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_dma.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_ecap.obj: ../Device/Common\ Sources/f2838x_ecap.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_ecap.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_epwm.obj: ../Device/Common\ Sources/f2838x_epwm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_epwm.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_gpio.obj: ../Device/Common\ Sources/f2838x_gpio.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_gpio.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_piectrl.obj: ../Device/Common\ Sources/f2838x_piectrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_piectrl.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_pievect.obj: ../Device/Common\ Sources/f2838x_pievect.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_pievect.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_sysctrl.obj: ../Device/Common\ Sources/f2838x_sysctrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_sysctrl.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Device/Common\ Sources/f2838x_usdelay.obj: ../Device/Common\ Sources/f2838x_usdelay.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="Device/Common Sources/f2838x_usdelay.d_raw" --obj_directory="Device/Common Sources" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


