################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
My\ Files/Src/Common_Memmap.obj: ../My\ Files/Src/Common_Memmap.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="My Files/Src/Common_Memmap.d_raw" --obj_directory="My Files/Src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

My\ Files/Src/Control_Variables.obj: ../My\ Files/Src/Control_Variables.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="My Files/Src/Control_Variables.d_raw" --obj_directory="My Files/Src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

My\ Files/Src/NPC_Hardware_Setup.obj: ../My\ Files/Src/NPC_Hardware_Setup.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="My Files/Src/NPC_Hardware_Setup.d_raw" --obj_directory="My Files/Src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

My\ Files/Src/NPC_Solution.obj: ../My\ Files/Src/NPC_Solution.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="My Files/Src/NPC_Solution.d_raw" --obj_directory="My Files/Src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

My\ Files/Src/PowerAnalyzer.obj: ../My\ Files/Src/PowerAnalyzer.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu32 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc --fp_mode=relaxed --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/My Files/Headers" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-c2000_22.6.2.LTS/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Common Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/Headers Include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Device/driverlib/inc" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/DCL_Control/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/FFT/include/fpu32" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/IQ_math/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Power Measurement/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Rampgen/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/Spll/include" --include_path="C:/Users/admin/Desktop/Anamitra Projects/C2000/SingleAndThreePhaseACPS/Inverter_Side_cpu1/Libraries/transforms" --advice:performance=all --define=CPU1 --define=DEBUG --define=_FLASH --define=_LAUNCHXL_F28388D -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="My Files/Src/PowerAnalyzer.d_raw" --obj_directory="My Files/Src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


